### ISSUE TITLE
Unable to run the app in pi due to fireba

### ISSUE THREAD

**Issue by loconous** [mars3725/MSB_Companion_App#2]
ERROR when launching in the pi:
flutter: Observatory listening on http://127.0.0.1:32933/8PSPe70lZAo=/
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)  
#0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1 MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:363:35)
<asynchronous suspension>
#2 MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:31:23)
<asynchronous suspension>
#3 MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
<asynchronous suspension>
#4 Firebase.initializeApp (package:firebase_core/src/firebase.dart:40:31)
<asynchronous suspension>
#5 main (package:msb_companion/main.dart:10:3)
<asynchronous suspension>

**Comment by loconous** [comment]
See https://github.com/ardera/flutter-pi/issues/161

I found one guy that made some, but they seem deprecated: https://github.com/bmcbarron/flutter-pi
